-- ============================================================================
-- Baseline schema — equivalent of the schema TypeORM `synchronize` produced from
-- the NestJS entities, PLUS the hand-applied stored procedures / triggers from
-- sql/kanban_tasks.sql that the services depend on (fn_set_ticket_id trigger,
-- fn_move_task, fn_reorder_task, fn_reorder_subtask).
--
-- Every statement is idempotent so this can also be applied to a database that
-- was already created by the Nest app (or use flyway baseline-on-migrate).
-- ============================================================================

CREATE EXTENSION IF NOT EXISTS "pgcrypto";
CREATE EXTENSION IF NOT EXISTS "uuid-ossp";

-- ---------------------------------------------------------------------------
-- Enum types (TypeORM default names: <table>_<column>_enum, unless enumName set)
-- ---------------------------------------------------------------------------
DO $$ BEGIN
  CREATE TYPE users_role_enum AS ENUM (
    'backend_developer','frontend_developer','fullstack_developer','qa','devops',
    'designer','product_manager','tech_lead');
EXCEPTION WHEN duplicate_object THEN NULL; END $$;

DO $$ BEGIN
  CREATE TYPE tasks_status_enum AS ENUM ('open','in_progress','in_review','done','cancelled');
EXCEPTION WHEN duplicate_object THEN NULL; END $$;

DO $$ BEGIN
  CREATE TYPE tasks_priority_enum AS ENUM ('no_priority','urgent','high','medium','low');
EXCEPTION WHEN duplicate_object THEN NULL; END $$;

DO $$ BEGIN
  CREATE TYPE notifications_type_enum AS ENUM ('comment_created','comment_mentioned','task_assigned','task_updated');
EXCEPTION WHEN duplicate_object THEN NULL; END $$;

DO $$ BEGIN
  CREATE TYPE project_role AS ENUM ('owner','admin','member','viewer');
EXCEPTION WHEN duplicate_object THEN NULL; END $$;
ALTER TYPE project_role ADD VALUE IF NOT EXISTS 'viewer';

DO $$ BEGIN
  CREATE TYPE task_subscription_source AS ENUM ('assigned','mentioned','commented','manual','created');
EXCEPTION WHEN duplicate_object THEN NULL; END $$;

DO $$ BEGIN
  CREATE TYPE task_activity_action AS ENUM (
    'task_created','task_title_updated','task_description_updated','task_status_changed',
    'task_priority_changed','task_due_date_changed','task_assignee_added','task_assignee_removed',
    'task_label_added','task_label_removed','task_moved','task_reordered');
EXCEPTION WHEN duplicate_object THEN NULL; END $$;

-- ---------------------------------------------------------------------------
-- users
-- ---------------------------------------------------------------------------
CREATE TABLE IF NOT EXISTS users (
  id            UUID PRIMARY KEY DEFAULT uuid_generate_v4(),
  email         VARCHAR(255) NOT NULL,
  full_name     VARCHAR(150) NOT NULL,
  password_hash TEXT NOT NULL,
  role          users_role_enum NOT NULL DEFAULT 'backend_developer',
  avatar_url    TEXT NOT NULL DEFAULT 'https://api.dicebear.com/9.x/initials/svg?seed=default',
  is_active     BOOLEAN NOT NULL DEFAULT true,
  created_at    TIMESTAMPTZ NOT NULL DEFAULT now(),
  updated_at    TIMESTAMPTZ NOT NULL DEFAULT now(),
  CONSTRAINT "UQ_users_email" UNIQUE (email)
);
CREATE INDEX IF NOT EXISTS idx_users_role ON users (role);
CREATE INDEX IF NOT EXISTS idx_users_is_active ON users (is_active);

-- ---------------------------------------------------------------------------
-- projects (id generated by the application: 8 alphanumeric chars)
-- ---------------------------------------------------------------------------
CREATE TABLE IF NOT EXISTS projects (
  id             VARCHAR(8) PRIMARY KEY,
  name           VARCHAR(100) NOT NULL,
  tag            VARCHAR(10) NOT NULL,
  ticket_counter INT NOT NULL DEFAULT 0,
  description    TEXT,
  created_by     UUID REFERENCES users(id) ON DELETE SET NULL,
  created_at     TIMESTAMPTZ NOT NULL DEFAULT now(),
  updated_at     TIMESTAMPTZ NOT NULL DEFAULT now(),
  CONSTRAINT "UQ_projects_name" UNIQUE (name),
  CONSTRAINT "UQ_projects_tag" UNIQUE (tag)
);

-- ---------------------------------------------------------------------------
-- project_members
-- ---------------------------------------------------------------------------
CREATE TABLE IF NOT EXISTS project_members (
  project_id VARCHAR(8) NOT NULL REFERENCES projects(id) ON DELETE CASCADE,
  user_id    UUID NOT NULL REFERENCES users(id) ON DELETE CASCADE,
  role       project_role NOT NULL DEFAULT 'member',
  joined_at  TIMESTAMPTZ NOT NULL DEFAULT now(),
  PRIMARY KEY (project_id, user_id)
);
CREATE INDEX IF NOT EXISTS idx_project_members_user_id ON project_members (user_id);

-- ---------------------------------------------------------------------------
-- refresh_tokens
-- ---------------------------------------------------------------------------
CREATE TABLE IF NOT EXISTS refresh_tokens (
  id          SERIAL PRIMARY KEY,
  user_id     UUID NOT NULL REFERENCES users(id) ON DELETE CASCADE,
  token_hash  TEXT NOT NULL,
  device_info VARCHAR(255),
  ip_address  VARCHAR(45),
  is_revoked  BOOLEAN NOT NULL DEFAULT false,
  expires_at  TIMESTAMPTZ NOT NULL,
  created_at  TIMESTAMPTZ NOT NULL DEFAULT now(),
  CONSTRAINT "UQ_refresh_tokens_token_hash" UNIQUE (token_hash)
);
CREATE INDEX IF NOT EXISTS idx_refresh_tokens_user_id ON refresh_tokens (user_id);

-- ---------------------------------------------------------------------------
-- teams / team_members (project scoped)
-- ---------------------------------------------------------------------------
CREATE TABLE IF NOT EXISTS teams (
  id          SERIAL PRIMARY KEY,
  name        VARCHAR(100) NOT NULL,
  description TEXT,
  color       VARCHAR(20),
  is_active   BOOLEAN NOT NULL DEFAULT true,
  project_id  VARCHAR(8) NOT NULL REFERENCES projects(id) ON DELETE CASCADE,
  created_at  TIMESTAMPTZ NOT NULL DEFAULT now(),
  updated_at  TIMESTAMPTZ NOT NULL DEFAULT now(),
  CONSTRAINT uq_teams_project_name UNIQUE (project_id, name)
);
CREATE INDEX IF NOT EXISTS idx_teams_is_active ON teams (is_active);
CREATE INDEX IF NOT EXISTS idx_teams_project_id ON teams (project_id);

CREATE TABLE IF NOT EXISTS team_members (
  team_id    INT NOT NULL REFERENCES teams(id) ON DELETE CASCADE,
  user_id    UUID NOT NULL REFERENCES users(id) ON DELETE CASCADE,
  project_id VARCHAR(8) NOT NULL,
  joined_at  TIMESTAMPTZ NOT NULL DEFAULT now(),
  PRIMARY KEY (team_id, user_id),
  CONSTRAINT "UQ_team_members_user_id_project_id" UNIQUE (user_id, project_id)
);
CREATE INDEX IF NOT EXISTS idx_team_members_user_id ON team_members (user_id);
CREATE INDEX IF NOT EXISTS idx_team_members_project_id ON team_members (project_id);

-- ---------------------------------------------------------------------------
-- kanban_columns
-- ---------------------------------------------------------------------------
CREATE TABLE IF NOT EXISTS kanban_columns (
  id          SERIAL PRIMARY KEY,
  name        VARCHAR(100) NOT NULL,
  position    INT NOT NULL DEFAULT 0,
  color       VARCHAR(20),
  is_archived BOOLEAN NOT NULL DEFAULT false,
  created_at  TIMESTAMPTZ NOT NULL DEFAULT now(),
  updated_at  TIMESTAMPTZ NOT NULL DEFAULT now(),
  project_id  VARCHAR(8) NOT NULL REFERENCES projects(id) ON DELETE RESTRICT,
  CONSTRAINT "UQ_kanban_columns_name" UNIQUE (name)
);
CREATE INDEX IF NOT EXISTS idx_kanban_columns_position ON kanban_columns (position);

-- ---------------------------------------------------------------------------
-- labels
-- ---------------------------------------------------------------------------
CREATE TABLE IF NOT EXISTS labels (
  id         SERIAL PRIMARY KEY,
  name       VARCHAR(50) NOT NULL,
  color      VARCHAR(20) NOT NULL,
  created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
  updated_at TIMESTAMPTZ NOT NULL DEFAULT now(),
  CONSTRAINT "UQ_labels_name" UNIQUE (name)
);

-- ---------------------------------------------------------------------------
-- tasks (+ join tables)
-- ---------------------------------------------------------------------------
CREATE TABLE IF NOT EXISTS tasks (
  id            UUID PRIMARY KEY DEFAULT uuid_generate_v4(),
  title         VARCHAR(255) NOT NULL,
  description   TEXT,
  status        tasks_status_enum NOT NULL DEFAULT 'open',
  priority      tasks_priority_enum NOT NULL DEFAULT 'no_priority',
  position      INT NOT NULL DEFAULT 0,
  ticket_id     VARCHAR(20),
  ticket_number INT,
  column_id     INT NOT NULL REFERENCES kanban_columns(id) ON DELETE RESTRICT,
  team_id       INT REFERENCES teams(id) ON DELETE SET NULL,
  created_by    UUID REFERENCES users(id) ON DELETE SET NULL,
  parent_id     UUID REFERENCES tasks(id) ON DELETE CASCADE,
  due_date      TIMESTAMPTZ,
  created_at    TIMESTAMPTZ NOT NULL DEFAULT now(),
  updated_at    TIMESTAMPTZ NOT NULL DEFAULT now(),
  CONSTRAINT "UQ_tasks_ticket_id" UNIQUE (ticket_id)
);
CREATE INDEX IF NOT EXISTS idx_tasks_status ON tasks (status);
CREATE INDEX IF NOT EXISTS idx_tasks_priority ON tasks (priority);
CREATE INDEX IF NOT EXISTS idx_tasks_column_id ON tasks (column_id);
CREATE INDEX IF NOT EXISTS idx_tasks_team_id ON tasks (team_id);
CREATE INDEX IF NOT EXISTS idx_tasks_created_by ON tasks (created_by);
CREATE INDEX IF NOT EXISTS idx_tasks_parent_id ON tasks (parent_id);

CREATE TABLE IF NOT EXISTS task_assignees (
  task_id UUID NOT NULL REFERENCES tasks(id) ON DELETE CASCADE,
  user_id UUID NOT NULL REFERENCES users(id) ON DELETE CASCADE,
  PRIMARY KEY (task_id, user_id)
);
CREATE INDEX IF NOT EXISTS idx_task_assignees_user_id ON task_assignees (user_id);

CREATE TABLE IF NOT EXISTS task_labels (
  task_id  UUID NOT NULL REFERENCES tasks(id) ON DELETE CASCADE,
  label_id INT NOT NULL REFERENCES labels(id) ON DELETE CASCADE,
  PRIMARY KEY (task_id, label_id)
);
CREATE INDEX IF NOT EXISTS idx_task_labels_label_id ON task_labels (label_id);

-- ---------------------------------------------------------------------------
-- task_comments
-- ---------------------------------------------------------------------------
CREATE TABLE IF NOT EXISTS task_comments (
  id         UUID PRIMARY KEY DEFAULT uuid_generate_v4(),
  content    TEXT NOT NULL,
  is_edited  BOOLEAN NOT NULL DEFAULT false,
  task_id    UUID NOT NULL REFERENCES tasks(id) ON DELETE CASCADE,
  author_id  UUID NOT NULL REFERENCES users(id) ON DELETE CASCADE,
  created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
  updated_at TIMESTAMPTZ NOT NULL DEFAULT now()
);
CREATE INDEX IF NOT EXISTS idx_task_comments_task_id ON task_comments (task_id);
CREATE INDEX IF NOT EXISTS idx_task_comments_author_id ON task_comments (author_id);

-- ---------------------------------------------------------------------------
-- notifications
-- ---------------------------------------------------------------------------
CREATE TABLE IF NOT EXISTS notifications (
  id           UUID PRIMARY KEY DEFAULT uuid_generate_v4(),
  type         notifications_type_enum NOT NULL,
  recipient_id UUID NOT NULL REFERENCES users(id) ON DELETE CASCADE,
  actor_id     UUID NOT NULL REFERENCES users(id) ON DELETE CASCADE,
  entity_type  VARCHAR(50) NOT NULL,
  entity_id    UUID NOT NULL,
  payload      JSONB NOT NULL DEFAULT '{}',
  is_read      BOOLEAN NOT NULL DEFAULT false,
  read_at      TIMESTAMPTZ,
  created_at   TIMESTAMPTZ NOT NULL DEFAULT now()
);
CREATE INDEX IF NOT EXISTS idx_notifications_type ON notifications (type);
CREATE INDEX IF NOT EXISTS idx_notifications_recipient_id ON notifications (recipient_id);
CREATE INDEX IF NOT EXISTS idx_notifications_actor_id ON notifications (actor_id);
CREATE INDEX IF NOT EXISTS idx_notifications_entity ON notifications (entity_id);
CREATE INDEX IF NOT EXISTS idx_notifications_recipient_unread ON notifications (recipient_id, is_read, created_at DESC);

-- ---------------------------------------------------------------------------
-- task_activities
-- ---------------------------------------------------------------------------
CREATE TABLE IF NOT EXISTS task_activities (
  id         UUID PRIMARY KEY DEFAULT uuid_generate_v4(),
  task_id    UUID NOT NULL REFERENCES tasks(id) ON DELETE CASCADE,
  actor_id   UUID NOT NULL REFERENCES users(id) ON DELETE CASCADE,
  action     task_activity_action NOT NULL,
  payload    JSONB NOT NULL DEFAULT '{}',
  created_at TIMESTAMPTZ NOT NULL DEFAULT now()
);
CREATE INDEX IF NOT EXISTS idx_task_activities_task_id ON task_activities (task_id);
CREATE INDEX IF NOT EXISTS idx_task_activities_actor_id ON task_activities (actor_id);
CREATE INDEX IF NOT EXISTS idx_task_activities_task_created ON task_activities (task_id, created_at DESC);

-- ---------------------------------------------------------------------------
-- task_subscriptions
-- ---------------------------------------------------------------------------
CREATE TABLE IF NOT EXISTS task_subscriptions (
  task_id    UUID NOT NULL REFERENCES tasks(id) ON DELETE CASCADE,
  user_id    UUID NOT NULL REFERENCES users(id) ON DELETE CASCADE,
  source     task_subscription_source NOT NULL DEFAULT 'manual',
  created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
  PRIMARY KEY (task_id, user_id)
);
CREATE INDEX IF NOT EXISTS idx_task_subscriptions_user_id ON task_subscriptions (user_id);

-- ============================================================================
-- Stored procedures & triggers (sql/kanban_tasks.sql §4 and §8)
-- ============================================================================
CREATE OR REPLACE FUNCTION fn_set_ticket_id()
RETURNS TRIGGER AS $$
DECLARE
    v_project_id VARCHAR(8);
    v_tag        VARCHAR(10);
    v_next_num   INT;
BEGIN
    SELECT kc.project_id INTO v_project_id
    FROM kanban_columns kc
    WHERE kc.id = NEW.column_id;

    IF v_project_id IS NULL THEN
        RAISE EXCEPTION 'Column % has no project', NEW.column_id;
    END IF;

    UPDATE projects
    SET ticket_counter = ticket_counter + 1
    WHERE id = v_project_id
    RETURNING ticket_counter, tag INTO v_next_num, v_tag;

    IF NOT FOUND THEN
        RAISE EXCEPTION 'Project % not found when generating ticket ID', v_project_id;
    END IF;

    IF v_tag IS NULL THEN
        RAISE EXCEPTION 'Project % has no tag assigned', v_project_id;
    END IF;

    NEW.ticket_number := v_next_num;
    NEW.ticket_id := v_tag || '-' || v_next_num;
    RETURN NEW;
END;
$$ LANGUAGE plpgsql;

DROP TRIGGER IF EXISTS trg_tasks_set_ticket_id ON tasks;
CREATE TRIGGER trg_tasks_set_ticket_id
    BEFORE INSERT ON tasks
    FOR EACH ROW
    EXECUTE FUNCTION fn_set_ticket_id();

CREATE OR REPLACE FUNCTION fn_move_task(
    p_task_id       UUID,
    p_new_column_id INT,
    p_new_position  INT
)
RETURNS VOID AS $$
DECLARE
    v_old_column_id INT;
    v_old_position  INT;
BEGIN
    SELECT column_id, position INTO v_old_column_id, v_old_position
    FROM tasks WHERE id = p_task_id;

    IF v_old_column_id IS NULL THEN
        RAISE EXCEPTION 'Task with id "%" not found', p_task_id;
    END IF;

    UPDATE tasks
    SET position = position - 1
    WHERE column_id = v_old_column_id
      AND position > v_old_position;

    UPDATE tasks
    SET position = position + 1
    WHERE column_id = p_new_column_id
      AND position >= p_new_position;

    UPDATE tasks
    SET column_id = p_new_column_id,
        position  = p_new_position
    WHERE id = p_task_id;
END;
$$ LANGUAGE plpgsql;

CREATE OR REPLACE FUNCTION fn_reorder_task(
    p_task_id      UUID,
    p_new_position INT
)
RETURNS VOID AS $$
DECLARE
    v_column_id    INT;
    v_old_position INT;
BEGIN
    SELECT column_id, position INTO v_column_id, v_old_position
    FROM tasks WHERE id = p_task_id;

    IF v_column_id IS NULL THEN
        RAISE EXCEPTION 'Task with id "%" not found', p_task_id;
    END IF;

    IF v_old_position = p_new_position THEN
        RETURN;
    END IF;

    IF p_new_position < v_old_position THEN
        UPDATE tasks
        SET position = position + 1
        WHERE column_id = v_column_id
          AND position >= p_new_position
          AND position < v_old_position;
    ELSE
        UPDATE tasks
        SET position = position - 1
        WHERE column_id = v_column_id
          AND position > v_old_position
          AND position <= p_new_position;
    END IF;

    UPDATE tasks SET position = p_new_position WHERE id = p_task_id;
END;
$$ LANGUAGE plpgsql;

CREATE OR REPLACE FUNCTION fn_reorder_subtask(
    p_subtask_id   UUID,
    p_parent_id    UUID,
    p_new_position INT
)
RETURNS VOID AS $$
DECLARE
    v_old_position INT;
BEGIN
    SELECT position INTO v_old_position
    FROM tasks WHERE id = p_subtask_id AND parent_id = p_parent_id;

    IF NOT FOUND THEN
        RAISE EXCEPTION 'Subtask "%" not found under parent "%"', p_subtask_id, p_parent_id;
    END IF;

    IF v_old_position = p_new_position THEN
        RETURN;
    END IF;

    IF p_new_position < v_old_position THEN
        UPDATE tasks
        SET position = position + 1
        WHERE parent_id = p_parent_id
          AND position >= p_new_position
          AND position < v_old_position;
    ELSE
        UPDATE tasks
        SET position = position - 1
        WHERE parent_id = p_parent_id
          AND position > v_old_position
          AND position <= p_new_position;
    END IF;

    UPDATE tasks SET position = p_new_position WHERE id = p_subtask_id;
END;
$$ LANGUAGE plpgsql;
